### ISSUE TITLE
TODO list for UX improvements

### ISSUE THREAD

**Issue by scriptSQD** [scriptSQD/sqdboards#9]
<h3>There's the list:</h3>

- [ ] Add spinning loaders wherever possible/makes sense, so that the user is aware of the component state.
- [ ] Add error and empty state placeholders so that the user knows if something failed.
- [ ] Add image zooming (this one is really tricky, I'll be trying with PhotoSwipe, but it did;t seem to work previously).
- [ ] Try to improve scrolling technique (esp. Chrome/Chromium based browsers, which make scroll-snapping really rough).

*It will eventually be updated with some new ideas and some completed ones.

**Comment by scriptSQD** [comment]
Image zooming seems to be implemented pretty nicely with Zoomist. We'll see how it goes in the perspective
